// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220720115752_BrandNewMigration")]
    partial class BrandNewMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Entities.AcBullet", b =>
                {
                    b.Property<int>("AcBulletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcBulletId"), 1L, 1);

                    b.Property<string>("AcBulletText")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("Order")
                        .HasColumnType("real");

                    b.Property<int>("StudInfoId")
                        .HasColumnType("int");

                    b.HasKey("AcBulletId");

                    b.HasIndex("StudInfoId");

                    b.ToTable("AcBullets");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"), 1L, 1);

                    b.Property<string>("AppUserType")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CiLocation")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CiempLocation")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassYear")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CoLocation")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("College")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpIndustry")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("EmpName")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("EmployeeNum")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("HrContactTitle")
                        .HasColumnType("varchar(75)");

                    b.Property<string>("IcfNote")
                        .HasColumnType("varchar(75)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Major")
                        .HasColumnType("varchar(60)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RegisterCode")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("StLocation")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StempLocation")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(60)");

                    b.HasKey("AppUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("API.Entities.CiempLocation", b =>
                {
                    b.Property<int>("CiempLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiempLocationId"), 1L, 1);

                    b.Property<string>("CiempLocationName")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CiempLocationSortName")
                        .HasColumnType("varchar(40)");

                    b.Property<int>("StempLocationId")
                        .HasColumnType("int");

                    b.HasKey("CiempLocationId");

                    b.HasIndex("StempLocationId");

                    b.ToTable("CiempLocations");
                });

            modelBuilder.Entity("API.Entities.CiLocation", b =>
                {
                    b.Property<int>("CiLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiLocationId"), 1L, 1);

                    b.Property<string>("CiLocationName")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CiLocationSortName")
                        .HasColumnType("varchar(40)");

                    b.Property<int>("StLocationId")
                        .HasColumnType("int");

                    b.HasKey("CiLocationId");

                    b.HasIndex("StLocationId");

                    b.ToTable("CiLocations");
                });

            modelBuilder.Entity("API.Entities.College", b =>
                {
                    b.Property<int>("CollegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollegeId"), 1L, 1);

                    b.Property<string>("CollegeName")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CollegeNickname")
                        .HasColumnType("varchar(30)");

                    b.HasKey("CollegeId");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("API.Entities.CoLocation", b =>
                {
                    b.Property<int>("CoLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoLocationId"), 1L, 1);

                    b.Property<string>("CoLocationName")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CoLocationSortName")
                        .HasColumnType("varchar(15)");

                    b.HasKey("CoLocationId");

                    b.ToTable("CoLocations");
                });

            modelBuilder.Entity("API.Entities.DutyBullet", b =>
                {
                    b.Property<int>("DutyBulletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DutyBulletId"), 1L, 1);

                    b.Property<string>("DutyBulletText")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("Order")
                        .HasColumnType("real");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("DutyBulletId");

                    b.HasIndex("PositionId");

                    b.ToTable("DutyBullets");
                });

            modelBuilder.Entity("API.Entities.EmpIndustry", b =>
                {
                    b.Property<int>("EmpIndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpIndustryId"), 1L, 1);

                    b.Property<string>("EmpIndustryName")
                        .HasColumnType("varchar(60)");

                    b.HasKey("EmpIndustryId");

                    b.ToTable("EmpIndustries");
                });

            modelBuilder.Entity("API.Entities.EmpInfo", b =>
                {
                    b.Property<int>("EmpInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpInfoId"), 1L, 1);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpWebsite")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UniqueContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueTitle")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("WhyWork")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpInfoId");

                    b.HasIndex("AppUserId");

                    b.ToTable("EmpInfos");
                });

            modelBuilder.Entity("API.Entities.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MajorName")
                        .HasColumnType("varchar(60)");

                    b.HasKey("MajorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("API.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MessageSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientAppUserType")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RecipientCollege")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RecipientCompany")
                        .HasColumnType("varchar(60)");

                    b.Property<bool>("RecipientDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RecipientFirstName")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientUsername")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("SenderAppUserType")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SenderCollege")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SenderCompany")
                        .HasColumnType("varchar(60)");

                    b.Property<bool>("SenderDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SenderFirstName")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderUsername")
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("API.Entities.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NewsContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsTitle")
                        .HasColumnType("varchar(80)");

                    b.Property<float>("Order")
                        .HasColumnType("real");

                    b.HasKey("NewsId");

                    b.ToTable("Newses");
                });

            modelBuilder.Entity("API.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainLogo")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PublicId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StudentUrl")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("API.Entities.PhotoHr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("HrUrl")
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsMainHr")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("PhotoHrs");
                });

            modelBuilder.Entity("API.Entities.PosCategory", b =>
                {
                    b.Property<int>("PosCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosCategoryId"), 1L, 1);

                    b.Property<string>("PosCategoryName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("PosCategoryId");

                    b.ToTable("PosCategories");
                });

            modelBuilder.Entity("API.Entities.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"), 1L, 1);

                    b.Property<DateTime?>("AppDeadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("ApplyEmail")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ApplyLink")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CiempLocation")
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("HowToApply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PosCategory")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PosName")
                        .HasColumnType("varchar(75)");

                    b.Property<string>("PositionBenefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionType")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("RegisterCode")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("varchar(75)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StempLocation")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UniqueContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueTitle")
                        .HasColumnType("varchar(100)");

                    b.HasKey("PositionId");

                    b.HasIndex("AppUserId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("API.Entities.PositName", b =>
                {
                    b.Property<int>("PositNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositNameId"), 1L, 1);

                    b.Property<int>("PosCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("PosName")
                        .HasColumnType("varchar(75)");

                    b.HasKey("PositNameId");

                    b.HasIndex("PosCategoryId");

                    b.ToTable("PositNames");
                });

            modelBuilder.Entity("API.Entities.ProfileAdvice", b =>
                {
                    b.Property<int>("ProfileAdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileAdviceId"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("Order")
                        .HasColumnType("real");

                    b.Property<string>("ProfileAdviceContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileAdviceTitle")
                        .HasColumnType("varchar(75)");

                    b.HasKey("ProfileAdviceId");

                    b.ToTable("ProfileAdvices");
                });

            modelBuilder.Entity("API.Entities.RegisterCode", b =>
                {
                    b.Property<int>("RegisterCodeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RegisterCodeName1")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeName2")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeName3")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeName4")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeName5")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeName6")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeName7")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeNameAdmin")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeNameOwner")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RegisterCodeNameStud")
                        .HasColumnType("varchar(15)");

                    b.HasKey("RegisterCodeId");

                    b.ToTable("RegisterCodes");
                });

            modelBuilder.Entity("API.Entities.SkillsBullet", b =>
                {
                    b.Property<int>("SkillsBulletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillsBulletId"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("Order")
                        .HasColumnType("real");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("SkillsBulletText")
                        .HasColumnType("varchar(250)");

                    b.HasKey("SkillsBulletId");

                    b.HasIndex("PositionId");

                    b.ToTable("SkillsBullets");
                });

            modelBuilder.Entity("API.Entities.StempLocation", b =>
                {
                    b.Property<int>("StempLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StempLocationId"), 1L, 1);

                    b.Property<string>("StempLocationName")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StempLocationSortName")
                        .HasColumnType("varchar(10)");

                    b.HasKey("StempLocationId");

                    b.ToTable("StempLocations");
                });

            modelBuilder.Entity("API.Entities.StLocation", b =>
                {
                    b.Property<int>("StLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StLocationId"), 1L, 1);

                    b.Property<int>("CoLocationId")
                        .HasColumnType("int");

                    b.Property<string>("StLocationName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StLocationSortName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StLocationId");

                    b.HasIndex("CoLocationId");

                    b.ToTable("StLocations");
                });

            modelBuilder.Entity("API.Entities.StudInfo", b =>
                {
                    b.Property<int>("StudInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudInfoId"), 1L, 1);

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Arts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Athletics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BestEmail")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BestPhone")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("DreamJob")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ExtraCurricular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPA")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("GradDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UniqueContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueTitle")
                        .HasColumnType("varchar(100)");

                    b.HasKey("StudInfoId");

                    b.HasIndex("AppUserId");

                    b.ToTable("StudInfos");
                });

            modelBuilder.Entity("API.Entities.UserLike", b =>
                {
                    b.Property<int>("SourceUserId")
                        .HasColumnType("int");

                    b.Property<int>("LikedUserId")
                        .HasColumnType("int");

                    b.HasKey("SourceUserId", "LikedUserId");

                    b.HasIndex("LikedUserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("API.Entities.WorkBullet", b =>
                {
                    b.Property<int>("WorkBulletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkBulletId"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("Order")
                        .HasColumnType("real");

                    b.Property<int>("StudInfoId")
                        .HasColumnType("int");

                    b.Property<string>("WorkBulletText")
                        .HasColumnType("varchar(250)");

                    b.HasKey("WorkBulletId");

                    b.HasIndex("StudInfoId");

                    b.ToTable("WorkBullets");
                });

            modelBuilder.Entity("API.Entities.AcBullet", b =>
                {
                    b.HasOne("API.Entities.StudInfo", "StudInfo")
                        .WithMany("AcBullets")
                        .HasForeignKey("StudInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudInfo");
                });

            modelBuilder.Entity("API.Entities.CiempLocation", b =>
                {
                    b.HasOne("API.Entities.StempLocation", "stempLocation")
                        .WithMany("CiempLocations")
                        .HasForeignKey("StempLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("stempLocation");
                });

            modelBuilder.Entity("API.Entities.CiLocation", b =>
                {
                    b.HasOne("API.Entities.StLocation", "stLocation")
                        .WithMany("CiLocations")
                        .HasForeignKey("StLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("stLocation");
                });

            modelBuilder.Entity("API.Entities.DutyBullet", b =>
                {
                    b.HasOne("API.Entities.Position", "Position")
                        .WithMany("DutyBullets")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("API.Entities.EmpInfo", b =>
                {
                    b.HasOne("API.Entities.AppUser", "AppUser")
                        .WithMany("EmpInfos")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.Major", b =>
                {
                    b.HasOne("API.Entities.Category", "Category")
                        .WithMany("Majors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("API.Entities.Message", b =>
                {
                    b.HasOne("API.Entities.AppUser", "Recipient")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Entities.AppUser", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("API.Entities.Photo", b =>
                {
                    b.HasOne("API.Entities.AppUser", "AppUser")
                        .WithMany("Photos")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.PhotoHr", b =>
                {
                    b.HasOne("API.Entities.AppUser", "AppUser")
                        .WithMany("PhotoHrs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.Position", b =>
                {
                    b.HasOne("API.Entities.AppUser", "AppUser")
                        .WithMany("Positions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.PositName", b =>
                {
                    b.HasOne("API.Entities.PosCategory", "PosCategory")
                        .WithMany("PositNames")
                        .HasForeignKey("PosCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosCategory");
                });

            modelBuilder.Entity("API.Entities.SkillsBullet", b =>
                {
                    b.HasOne("API.Entities.Position", "Position")
                        .WithMany("SkillsBullets")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("API.Entities.StLocation", b =>
                {
                    b.HasOne("API.Entities.CoLocation", "coLocation")
                        .WithMany("StLocations")
                        .HasForeignKey("CoLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("coLocation");
                });

            modelBuilder.Entity("API.Entities.StudInfo", b =>
                {
                    b.HasOne("API.Entities.AppUser", "AppUser")
                        .WithMany("StudInfos")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.UserLike", b =>
                {
                    b.HasOne("API.Entities.AppUser", "LikedUser")
                        .WithMany("LikedByUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("API.Entities.AppUser", "SourceUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LikedUser");

                    b.Navigation("SourceUser");
                });

            modelBuilder.Entity("API.Entities.WorkBullet", b =>
                {
                    b.HasOne("API.Entities.StudInfo", "StudInfo")
                        .WithMany("WorkBullets")
                        .HasForeignKey("StudInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudInfo");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Navigation("EmpInfos");

                    b.Navigation("LikedByUsers");

                    b.Navigation("LikedUsers");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("PhotoHrs");

                    b.Navigation("Photos");

                    b.Navigation("Positions");

                    b.Navigation("StudInfos");
                });

            modelBuilder.Entity("API.Entities.Category", b =>
                {
                    b.Navigation("Majors");
                });

            modelBuilder.Entity("API.Entities.CoLocation", b =>
                {
                    b.Navigation("StLocations");
                });

            modelBuilder.Entity("API.Entities.PosCategory", b =>
                {
                    b.Navigation("PositNames");
                });

            modelBuilder.Entity("API.Entities.Position", b =>
                {
                    b.Navigation("DutyBullets");

                    b.Navigation("SkillsBullets");
                });

            modelBuilder.Entity("API.Entities.StempLocation", b =>
                {
                    b.Navigation("CiempLocations");
                });

            modelBuilder.Entity("API.Entities.StLocation", b =>
                {
                    b.Navigation("CiLocations");
                });

            modelBuilder.Entity("API.Entities.StudInfo", b =>
                {
                    b.Navigation("AcBullets");

                    b.Navigation("WorkBullets");
                });
#pragma warning restore 612, 618
        }
    }
}
